baseurl = "https://stoic-carson-ecfaa2.netlify.com" # need to change once get rbind.io set up.
languageCode = "en"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
title = "Uncoast Unconf"
theme = "vex-hugo"

[params]
  description = ""

  # Put your custom stylesheets and scripts
  custom_stylesheets = []
  custom_scripts = []

  # Additional meta
  [[params.meta]]
    name = ""
    description = ""

  # Navigation bar informations
  [params.navbar]
    logo = "#uncoastUnconf"
    [[params.navbar.menu]]
      link = "/"
      text = "HOME"
    [[params.navbar.menu]]
      link = "#feature"
      text = "ABOUT"
    [[params.navbar.menu]]
      link = "http://bit.ly/uncoastUnconf19"
      text = "APPLY"
    [[params.navbar.menu]]
      link = "mailto:sctyner@iastate.edu"
      text = "CONTACT"
    [[params.navbar.menu]]
      link = "/CoC.md"
      text = "CODE OF CONDUCT"

  # Header
  [params.header]
    title = "The Uncoast Unconference"
    text = "Bringing R users and developers together in flyover country."
    [params.header.image]
      path = "images/templogo.png"
      alt = "Uncoastal"
    [params.header.button]
      link = "http://bit.ly/uncoastUnconf19" # in draft status rn.
      text = "Apply here!"
      # want button to have color #135FB2 and color #BEC0C3 on hover

  # about
  [params.features]
    title = "The Details"
    [params.features.image]
      path = "images/map.png"
      alt = "Location"
    # Menu at the left of the image
    [[params.features.left]]
      icon = "tf-calendar2"
      title = "When"
      text = "April 14-16, 2019"
    [[params.features.left]]
      icon = "tf-map2"
      title = "Where"
      text = "John Deere Financial in Des Moines, IA"
    [[params.features.left]]
      icon = "tf-ion-person-add"
      title = "Who"
      text = "You!"
    # Menu at the right of the image
    [[params.features.right]]
      icon = "tf-ion-calendar"
      title = "April 14"
      text = "An optional 'Day Zero' workshop for learning how to write R packages and collaborate with Github."
    [[params.features.right]]
      icon = "tf-ion-calendar"
      title = "April 15"
      text = "Day 1: Start with some introductions, form project groups, and go!"
    [[params.features.right]]
      icon = "tf-ion-calendar"
      title = "April 16"
      text = "Day 2: Continue to work on projects, group discussions, report out, dinner as a group."

  [params.promo]
    title = "What is an unconference?"
    text = "Unlike a conference with scheduled sessions and the mere hope of future collaboration, at an unconference, the collaboration happens in real time! R users and developers of all different backgrounds and levels come together for two days to collaborate on exciting data science projects. In addition, we will be hosting a Day 0 workshop for participants who are new to package development and collaboration with Github. (Photo credit: Karthik Ram and ROpenSci)"
    [params.promo.image]
      path = "images/karthik-runconf17.png"
      alt = "What is an unconf?"

  [params.feature_list]
    title = "Participants"
    [[params.feature_list.items]]
      image = "https://pbs.twimg.com/profile_images/205337390/robstat_400x400.png" 
      title = "Yihui Xie"
      subtitle = "Location: Omaha, Nebraska"
      text = "Yihui Xie is a software engineer at RStudio. He earned his PhD from the Department of Statistics, Iowa State University. He is interested in interactive statistical graphics and statistical computing. As an active R user, he has authored several R packages, such as knitr, bookdown, blogdown, xaringan, tinytex, animation, DT, tufte, formatR, fun, xfun, mime, highr, servr, and Rd2roxygen, among which the animation package won the 2009 John M. Chambers Statistical Software Award (ASA). He also co-authored a few other R packages, including shiny, rmarkdown, and leaflet. He has authored two books, Dynamic Documents with knitr (Xie 2015), and bookdown: Authoring Books and Technical Documents with R Markdown (Xie 2016), and co-authored two book, blogdown: Creating Websites with R Markdown (Xie, Hill, and Thomas 2017), and R Markdown: The Definitive Guide (Xie, Allaire, and Grolemund 2018)." # more bio? 
      button_link = "https://yihui.name"
      button_text = "Yihui's Website"
#    [[params.feature_list.items]]
#      image = "https://pbs.twimg.com/profile_images/452916682550308864/BrzrjV5i_400x400.jpeg"
#      title = "Winston Chang"
#      subtitle = "Location: Minneapolis, Minnesota"
#      text = "Software Developer, RStudio (Location: Minneapolis, MN)"
#      button_link = "https://github.com/wch"
#      button_text = "Winston's Github" 
#    [[params.feature_list.items]]
#      image = "https://pbs.twimg.com/profile_images/1055552227660759043/8xR6ZFfI_400x400.jpg"
#      title = "Amelia McNamara"
#      subtitle = "Location: St. Paul, Minnesota"
#      text = "Amelia is an Assistant Professor at the University of St Thomas in the department of  Department of Computer & Information Sciences. She earned her PhD in Statistics from UCLA. Her research interests include statistics education, statistical computing, data visualization, and spatial statistics. At the moment, she is also very interested in the effects of parameter choices on data analysis, particularly data visualizations."
#      button_link = "http://www.amelia.mn/"
#      button_text = "Amelia's Website" 

  [params.gallery]
    title = "Pictures from Similar Events"
    text = "Thanks to Mauro Lepore and Nistara Randhawa for the photos from other unconferences!"
    # Set the image directory to use as base
    directory = "images/showcase"
    # Set the images to show in the gallery
    images = ["ropensci-unconf17-checkers-nistara-randhawa.png", "mauro-runconf18-1.png", "mauro-runconf18-5.png", "mauro-runconf18-2.png", "mauro-runconf18-3.png", "mauro-runconf18-4.png", "mauro-runconf18-6.png", "mauro-runconf18-7.png"]

#  [params.call_to_action]
#    title = "Get Product Updates"
#    text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod"
#    placeholder = "Your Email Address Here"
#    button_text = "Subscribe"

  [params.testimonials]
    title = "Organizers"
    [[params.testimonials.blocks]]
      text = "Sam earned her PhD in Statistics from Iowa State University in 2017. Her primary research interests are data visualization and forensic statistics. She writes about both of these things on her <a href='https://sctyner.github.io/'>website</a>."
      name = "Sam Tyner"
      position = "Postdoc Research Associate, Iowa State University"
      image = "images/sam-headshot.png"
    [[params.testimonials.blocks]]
      text = "Sam holds an MS in statistics from Iowa State University. Before starting his current position, he worked in applied analytics roles within John Deere Worldwide Parts and Global Order Fulfillment."
      name = "Sam Helmich"
      position = "Principal Data Scientist, John Deere Intelligent Solutions Group"
      image = "images/samh-headshot.png"
    [[params.testimonials.blocks]]
      text = "Ian's background is in Mechanical Engineering and Computational Fluid Dynamics. As Schneider Electric became more data-centric, he learned R, and soon became an R visualization enthusiast. Since joining the ISU Statistical Graphics Working Group, Ian has become an R expert!"
      name = "Ian Lyttle"
      position = "Data Scientist, Schneider Electric"
      image = "images/ian-headshot.png"
    [[params.testimonials.blocks]]
      text = "Susan got her PhD from Iowa State University in 2015. She is currently working on research in statistical graphics and forensic statistics."
      name = "Susan Vanderplas"
      position = "Research Assistant Professor, Iowa State University"
      image = "images/susan-headshot.png"
    [[params.testimonials.blocks]]
      text = "Quote or bio. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, inventore?"
      name = "Angela Li"
      position = "R-Ladies Chicago, University of Chicago"
      image = "images/avater.png"  
    [[params.testimonials.blocks]]
      text = "Heike's primary research interests are Data Visualization, Multivariate Categorical Data Analysis, Statistical Computing, Exploratory Data Analysis and Interactive Statistical Graphics. She is also a member of the ISU Data Science Curriculum Committee."
      name = "Heike Hofmann"
      position = "Professor of Statistics, Iowa State University"
      image = "images/heike-headshot.png"
    [params.testimonials.button]
      link = "http://bit.ly/uncoastUnconf19"
      text = "Apply here!"

  # Footer uses navbar data
